[package]
name = "bevy_roguelike_tut"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.13", features = ["dynamic_linking"] }
bevy-inspector-egui = "0.23.4"
bevy_mod_debugdump = "0.10.0"
rand = "0.8.5"

[features]
default = []
flow = []
